name: Package Request
description: Request the addition of a new package to the project.
title: "Package Request: <패키지명>"
labels: ["package request"]

body:
  - type: markdown
    attributes:
      value: >
        새로운 패키지 추가 요청 양식입니다.
        
  - type: input
    id: package_name
    attributes:
      label: (필수) 패키지명
      description: 추가를 요청하는 패키지의 이름을 입력해주세요.
      placeholder: "pandas"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: (선택) 버전
      description: 특정 버전이 필요한 경우 명시해주세요.
      placeholder: "1.5.0"
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: (필수) 체크리스트
      description: 다음 사항을 모두 확인하고 체크해주세요.
      options:
        - label: 패키지명이 정확한지 확인했습니다.
          required: true
        - label: 패키지의 특정 버전이 필요한 경우 명시했습니다. (버전 미표기 시 최신 버전으로 반영됩니다)
          required: true
